export const ActionsTypes={
    SET_PRODUCTS:"SET_PRODUCTS",
    SELECTED_PRODUCT:"SELECTED_PRODUCT",
    CATEGORY_PRODUCTS:"CATEGORY_PRODUCTS",
    CATEGORY_PRODUCT:"CATEGORY_PRODUCT",
    All_USERS:"ALL_USERS"
    }

     